- id: check-no-special-commits
  name: Check for special commits
  description: prevents unintentional pushes of commits with special prefixes.
  entry: check-no-special-commits
  args:
    - "squash! "
    - "fixup! "
    - "amend! "
  language: python
  pass_filenames: false
  require_serial: true
  stages: [push, manual]
